name: macOS build
on:
  push:
    branches: [ master, dev ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: macos-latest
    env:
      KVXOPT_BUILD_GSL: 1
      KVXOPT_BUILD_FFTW: 1
      KVXOPT_BUILD_GLPK: 1
      KVXOPT_BUILD_OSQP: 1
      KVXOPT_BUILD_DSDP: 0
      SUITESPARSE_VERSION: 5.10.1
      SUITESPARSE_SHA256: acb4d1045f48a237e70294b950153e48dce5b5f9ca8190e86c2b8c54ce00a7ee

    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        suite-sparse: [lib_suitesparse]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coveralls numpy

      - name: Install libraries
        run: |
            brew install openblas glpk gsl fftw osqp

      - name: Config suite-sparse library
        run:
            brew install suite-sparse
        if: ${{ matrix.suite-sparse == 'lib_suitesparse' }}

      - name: Config suite-sparse source
        run: |
            wget https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v${SUITESPARSE_VERSION}.tar.gz
            echo "${SUITESPARSE_SHA256}  v${SUITESPARSE_VERSION}.tar.gz" > SuiteSparse.sha256
            shasum -a 256 -c SuiteSparse.sha256
            tar -xf v${SUITESPARSE_VERSION}.tar.gz
            echo "KVXOPT_SUITESPARSE_SRC_DIR=${{ github.workspace}}/SuiteSparse-${{ env.SUITESPARSE_VERSION }}" >> $GITHUB_ENV
        if: ${{ matrix.suite-sparse == 'src_suitesparse' }}

      - name: Install
        run: |
          python setup.py build
          pip install .

      - name: Test
        run: |
          echo ${KVXOPT_SUITESPARSE_SRC_DIR}
          python -c 'from kvxopt import blas,lapack,glpk,osqp,fftw,gsl,cholmod,umfpack,klu'
          py.test --cov=kvxopt tests/
