name: Windows build 2.7 with MINGW
on:
  push:
    branches: [ master, dev ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest
    env:
      KVXOPT_BUILD_GSL: 1
      KVXOPT_BUILD_FFTW: 1
      KVXOPT_BUILD_GLPK: 1
      KVXOPT_BUILD_DSDP: 0
      KVXOPT_BUILD_OSQP: 1
      SUITESPARSE_VERSION: 5.8.1
      SUITESPARSE_SHA256: 06726e471fbaa55f792578f9b4ab282ea9d008cf39ddcc3b42b73400acddef40
      OSQP_VERSION: 0.6.2

    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7]
        suite-sparse: [lib_suitesparse, src_suitesparse]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: coreutils unzip git make

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coveralls wheel numpy

      - name: Install libraries
        shell: msys2 {0}
        run: |
            pacman -S --noconfirm mingw-w64-x86_64-lapack mingw-w64-x86_64-gsl mingw-w64-x86_64-fftw mingw-w64-x86_64-glpk mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc
            echo "KVXOPT_GSL_LIB_DIR=$(cygpath -m /mingw64/lib)" >> $GITHUB_ENV
            echo "KVXOPT_GSL_INC_DIR=$(cygpath -m /mingw64/include)" >> $GITHUB_ENV
            echo "KVXOPT_FFTW_LIB_DIR=$(cygpath -m /mingw64/lib)" >> $GITHUB_ENV
            echo "KVXOPT_FFTW_INC_DIR=$(cygpath -m /mingw64/include)" >> $GITHUB_ENV
            echo "KVXOPT_GLPK_LIB_DIR=$(cygpath -m /mingw64/lib)" >> $GITHUB_ENV
            echo "KVXOPT_GLPK_INC_DIR=$(cygpath -m /mingw64/include)" >> $GITHUB_ENV
            echo "KVXOPT_BLAS_LIB_DIR=$(cygpath -m /mingw64/lib)" >> $GITHUB_ENV
            echo "$(cygpath -m /mingw64/bin)" >> $GITHUB_PATH

      - name: Config suite-sparse library windows
        shell: msys2 {0}
        run: |
            pacman -S --noconfirm mingw-w64-x86_64-suitesparse
            echo "KVXOPT_SUITESPARSE_LIB_DIR=$(cygpath -m /mingw64/lib)" >> $GITHUB_ENV
            echo "KVXOPT_SUITESPARSE_INC_DIR=$(cygpath -m /mingw64/include)" >> $GITHUB_ENV
        if: ${{ matrix.suite-sparse == 'lib_suitesparse' }}

      - name: Config suite-sparse source
        shell: msys2 {0}
        run: |
            wget https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v${SUITESPARSE_VERSION}.tar.gz
            echo "${SUITESPARSE_SHA256}  v${SUITESPARSE_VERSION}.tar.gz" > SuiteSparse.sha256
            shasum -a 256 -c SuiteSparse.sha256
            tar -xf v${SUITESPARSE_VERSION}.tar.gz
            echo "KVXOPT_SUITESPARSE_SRC_DIR=${{ github.workspace}}/SuiteSparse-${{ env.SUITESPARSE_VERSION }}" >> $GITHUB_ENV
        if: ${{ matrix.suite-sparse == 'src_suitesparse' }}

      - name: Get OSQP
        shell: msys2 {0}
        run: |
            git clone --recursive https://github.com/oxfordcontrol/osqp.git
            cd osqp
            git checkout v${{ env.OSQP_VERSION }}

      - name: Compile OSQP
        shell: msys2 {0}
        run: |
            cd osqp
            mkdir build
            cd build
            export CC=$(cygpath -m /mingw64/bin)/gcc
            export CXX=$(cygpath -m /mingw64/bin)/g++

            cmake -G "MSYS Makefiles" -D CMAKE_INSTALL_PREFIX=dist -D CMAKE_C_COMPILER_WORKS=1 -D CMAKE_CXX_COMPILER_WORKS=1 -D CMAKE_MAKE_PROGRAM=make ..
            make
            make install

      - name: Set OSQP path
        shell: msys2 {0}
        run: |
            echo "KVXOPT_OSQP_LIB_DIR=${{ github.workspace}}/osqp/build/dist/lib" >> $GITHUB_ENV
            echo "KVXOPT_OSQP_INC_DIR=${{ github.workspace}}/osqp/build/dist/include/osqp" >> $GITHUB_ENV

      - name: Install (windows)
        run: |
          python setup.py build --compiler=mingw32
          python setup.py bdist_wheel
          python -m pip install --no-index --find-links=dist kvxopt

      - name: Test
        run: |
          python -c 'from kvxopt import blas,lapack,glpk,osqp,fftw,gsl,cholmod,umfpack,klu'
          py.test --cov=kvxopt tests/
